# Generated by Django 4.1 on 2022-12-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accionistas', '0002_alter_accionista_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accionista',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='accionista',
            name='observacion',
            field=models.CharField(max_length=50),
        ),
    ]
